export const HOME_ROUTE = '/'
export const ADMIN_ROUTE = '/admin'
export const LOGIN_ROUTE = '/login'
export const SIGNUP_ROUTE = '/signup'
export const FAVORITE_ROUTE = '/favorite'
export const CART_ROUTE = '/cart'
export const BOOKS_ROUTE = '/books'